version: '2'
services:
  blog:
    # restart: always
    # build: ./app
    image: gevin/octblog
    ports:
      - "8000:8000"
    links:
      - mongo:mongo
    # volumes:
    #   - /usr/src/app/static
    env_file: .env

  mongo:
    # restart: always
    image: mongo:3.2
    env_file: .env

    volumes:
      - /data/db

