version: '2'
services:
  blog:
    # restart: always
    image: gevin/octblog:0.4
    # ports:
    #   - "8000:8000"
      # - "5000:5000"
    links:
      - mongo:mongo
    env_file: .env
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000

  mongo:
    # restart: always
    image: mongo:3.2

    volumes:
      - /Users/gevin/projects/data/mongodb:/data/db

    # ports:
    #   - "27017:27017"

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro